# Generated by Django 2.2.7 on 2020-02-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='pictures/')),
                ('title', models.CharField(max_length=100)),
                ('category', models.TextField(max_length=100)),
                ('about', models.TextField(max_length=1024)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('publish', models.DateTimeField(default='2020-02-05 13:36:35')),
            ],
        ),
    ]
