# Generated by Django 2.2.7 on 2020-01-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('pasw', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('regdate', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
